#!/bin/bash

file="/snapraid.sync"
current=`date +%s`
last_modified=`stat -c "%Y" $file`

getstatus()
{
   nothing_to_do=`sed -n '$p' $file`;
   everything_ok=`sed -n ':a;${P;q};N;12,$D;ba' < $file`
   if [[ $nothing_to_do == *"Nothing to do"* || $everything_ok == *"Everything OK"* ]]
   then
      status="OK";
   else
      status="$everything_ok";
   fi
}

checkit()
{
   if [ $status == "OK" ]
   then
      echo "Snapilicious, all snapped up!";
   else
      echo "Bummer, that did not snap right!\n$status";
   fi
}

snapit()
{
   snapraid sync > $file 2>&1;
}

getstatus;

if [ $(($current-$last_modified)) -gt 86400 ]
then
      snapit;
      getstatus;
      checkit;
elif [ "$status" == "OK" ]
then
      echo "All izz well!";
else
      snapit;
      getstatus;
      checkit;
fi
exit
