#!/bin/bash

#sync output file
file="/snapraid.sync"
current=`date +%s`
last_modified=`stat -c "%Y" $file`

#check status of last sync
getstatus()
{
   #last line of output file -eq "Nothing to do"
   nothing_to_do=`sed -n '$p' $file`;
   #output of 12th last line of output file
   everything_ok=`sed -n ':a;${P;q};N;12,$D;ba' < $file`
   if [[ $nothing_to_do == *"Nothing to do"* || $everything_ok == *"Everything OK"* ]]
   then
      status="OK";
   else
      status="$everything_ok";
   fi
}

#output status of last sync
checkit()
{
   if [ $status == "OK" ]
   then
      echo "Snapilicious, all snapped up!";
   else
      echo "Bummer, that did not snap right!\n$status";
   fi
}

#sync and save output to $file
snapit()
{
   snapraid sync > $file 2>&1;
}

getstatus;

#modify value for more frequent syncs
if [ $(($current-$last_modified)) -gt 86400 ]
then
      snapit;
      getstatus;
      checkit;
elif [ "$status" != "OK" ]
then
      snapit;
      getstatus;
      checkit;
else
      echo "All izz well!";
fi
exit
